// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recrutement_api.Data;

#nullable disable

namespace Recrutement_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409162009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recrutement_api.Models.AnalyseCV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<string>("Competences")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .HasColumnType("text");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<string>("TexteExtrait")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("AnalysesCV");
                });

            modelBuilder.Entity("Recrutement_api.Models.AssignationExpert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssigneLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OffreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OffreId", "ExpertId")
                        .IsUnique();

                    b.ToTable("AssignationsExperts");
                });

            modelBuilder.Entity("Recrutement_api.Models.AvisExpert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExpertId")
                        .HasColumnType("uuid");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.HasIndex("ExpertId");

                    b.ToTable("AvisExperts");
                });

            modelBuilder.Entity("Recrutement_api.Models.Candidat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Candidats");
                });

            modelBuilder.Entity("Recrutement_api.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("text");

                    b.Property<string>("Github")
                        .HasColumnType("text");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Seeking")
                        .HasColumnType("text");

                    b.Property<string>("SkillsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("Recrutement_api.Models.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormulaireResponses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OffreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("OffreId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("Recrutement_api.Models.ChampPersonnalise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstObligatoire")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FormulaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormulaireId");

                    b.ToTable("ChampsPersonnalises");
                });

            modelBuilder.Entity("Recrutement_api.Models.Entreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RNE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("Recrutement_api.Models.EntretienIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateScheduled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.ToTable("EntretiensIA");
                });

            modelBuilder.Entity("Recrutement_api.Models.Expert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInvited")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poste")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemporaryPassword")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique();

                    b.ToTable("Experts");
                });

            modelBuilder.Entity("Recrutement_api.Models.FormulaireCandidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OffreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OffreId")
                        .IsUnique();

                    b.ToTable("FormulairesCandidature");
                });

            modelBuilder.Entity("Recrutement_api.Models.OffreEmploi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublicLinkEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicLinkExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicToken")
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("OffresEmploi");
                });

            modelBuilder.Entity("Recrutement_api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Recrutement_api.Models.TenantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HiringStatus")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("TechStackJson")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Twitter")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("WorkTypesJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantProfiles");
                });

            modelBuilder.Entity("Recrutement_api.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Recrutement_api.Models.AnalyseCV", b =>
                {
                    b.HasOne("Recrutement_api.Models.Candidature", "Candidature")
                        .WithOne("AnalyseCV")
                        .HasForeignKey("Recrutement_api.Models.AnalyseCV", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("Recrutement_api.Models.AssignationExpert", b =>
                {
                    b.HasOne("Recrutement_api.Models.Expert", "Expert")
                        .WithMany("Assignations")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrutement_api.Models.OffreEmploi", "Offre")
                        .WithMany("Assignations")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Recrutement_api.Models.AvisExpert", b =>
                {
                    b.HasOne("Recrutement_api.Models.Candidature", "Candidature")
                        .WithMany("Avis")
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrutement_api.Models.Expert", "Expert")
                        .WithMany("Avis")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("Recrutement_api.Models.Candidat", b =>
                {
                    b.HasOne("Recrutement_api.Models.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("Recrutement_api.Models.Candidat", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Recrutement_api.Models.CandidateProfile", b =>
                {
                    b.HasOne("Recrutement_api.Models.Candidat", "Candidat")
                        .WithOne()
                        .HasForeignKey("Recrutement_api.Models.CandidateProfile", "CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("Recrutement_api.Models.Candidature", b =>
                {
                    b.HasOne("Recrutement_api.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recrutement_api.Models.OffreEmploi", "Offre")
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Recrutement_api.Models.ChampPersonnalise", b =>
                {
                    b.HasOne("Recrutement_api.Models.FormulaireCandidature", "Formulaire")
                        .WithMany("ChampsPersonnalises")
                        .HasForeignKey("FormulaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulaire");
                });

            modelBuilder.Entity("Recrutement_api.Models.Entreprise", b =>
                {
                    b.HasOne("Recrutement_api.Models.Tenant", "Tenant")
                        .WithMany("Entreprises")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Recrutement_api.Models.EntretienIA", b =>
                {
                    b.HasOne("Recrutement_api.Models.Candidature", "Candidature")
                        .WithMany()
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("Recrutement_api.Models.Expert", b =>
                {
                    b.HasOne("Recrutement_api.Models.Entreprise", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recrutement_api.Models.Entreprise", "Entreprise")
                        .WithMany("Experts")
                        .HasForeignKey("EntrepriseId");

                    b.HasOne("Recrutement_api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Recrutement_api.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Company");

                    b.Navigation("Entreprise");

                    b.Navigation("Tenant");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Recrutement_api.Models.FormulaireCandidature", b =>
                {
                    b.HasOne("Recrutement_api.Models.OffreEmploi", "Offre")
                        .WithOne("Formulaire")
                        .HasForeignKey("Recrutement_api.Models.FormulaireCandidature", "OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Recrutement_api.Models.OffreEmploi", b =>
                {
                    b.HasOne("Recrutement_api.Models.Entreprise", "Entreprise")
                        .WithMany("Offres")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Recrutement_api.Models.Tenant", b =>
                {
                    b.HasOne("Recrutement_api.Models.Utilisateur", "Utilisateur")
                        .WithOne()
                        .HasForeignKey("Recrutement_api.Models.Tenant", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Recrutement_api.Models.TenantProfile", b =>
                {
                    b.HasOne("Recrutement_api.Models.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("Recrutement_api.Models.TenantProfile", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Recrutement_api.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("Recrutement_api.Models.Candidature", b =>
                {
                    b.Navigation("AnalyseCV")
                        .IsRequired();

                    b.Navigation("Avis");
                });

            modelBuilder.Entity("Recrutement_api.Models.Entreprise", b =>
                {
                    b.Navigation("Experts");

                    b.Navigation("Offres");
                });

            modelBuilder.Entity("Recrutement_api.Models.Expert", b =>
                {
                    b.Navigation("Assignations");

                    b.Navigation("Avis");
                });

            modelBuilder.Entity("Recrutement_api.Models.FormulaireCandidature", b =>
                {
                    b.Navigation("ChampsPersonnalises");
                });

            modelBuilder.Entity("Recrutement_api.Models.OffreEmploi", b =>
                {
                    b.Navigation("Assignations");

                    b.Navigation("Candidatures");

                    b.Navigation("Formulaire")
                        .IsRequired();
                });

            modelBuilder.Entity("Recrutement_api.Models.Tenant", b =>
                {
                    b.Navigation("Entreprises");
                });
#pragma warning restore 612, 618
        }
    }
}
